#!/usr/bin/env bash
# Install HolmesGPT, wired to VictoriaMetrics, VictoriaLogs, Grafana and GitHub.
set -euo pipefail
source "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/lib/common.sh"
load_env
setup_docker_config

step "HolmesGPT ${VER_HOLMES}"

# ---------------------------------------------------------------------------
# LLM credentials
# ---------------------------------------------------------------------------
log "creating LLM secret"
k -n "${NS_HOLMES}" create secret generic holmes-llm-keys \
  --from-literal=OPENROUTER_API_KEY="${OPENROUTER_API_KEY}" \
  --dry-run=client -o yaml | k apply -f - >/dev/null
ok "holmes-llm-keys"

# ---------------------------------------------------------------------------
# Grafana service account token.
#
# The grafana/dashboards toolset authenticates with a service account token,
# not the admin password. Mint one through Grafana's HTTP API from inside the
# cluster. Idempotent: an existing service account is reused and simply issued
# a fresh token.
# ---------------------------------------------------------------------------
mint_grafana_token() {
  local auth="${GRAFANA_ADMIN_USER}:${GRAFANA_ADMIN_PASSWORD}"
  local sa_name="holmesgpt"

  # Look for an existing service account.
  local sa_id
  sa_id=$(incluster_curl "${NS_MONITORING}" -u "${auth}" \
            "${URL_GRAFANA}/api/serviceaccounts/search?query=${sa_name}" 2>/dev/null \
          | python3 -c '
import sys, json
try:
    for a in json.load(sys.stdin).get("serviceAccounts", []):
        if a.get("name") == "holmesgpt":
            print(a["id"]); break
except Exception:
    pass
' 2>/dev/null || true)

  if [[ -z "${sa_id}" ]]; then
    sa_id=$(incluster_curl "${NS_MONITORING}" -u "${auth}" \
              -X POST "${URL_GRAFANA}/api/serviceaccounts" \
              -H 'Content-Type: application/json' \
              -d '{"name":"holmesgpt","role":"Viewer","isDisabled":false}' 2>/dev/null \
            | python3 -c 'import sys,json; print(json.load(sys.stdin)["id"])' 2>/dev/null || true)
  fi

  [[ -n "${sa_id}" ]] || return 1

  # Token names must be unique per service account.
  incluster_curl "${NS_MONITORING}" -u "${auth}" \
    -X POST "${URL_GRAFANA}/api/serviceaccounts/${sa_id}/tokens" \
    -H 'Content-Type: application/json' \
    -d "{\"name\":\"holmesgpt-$(date +%s)\"}" 2>/dev/null \
  | python3 -c 'import sys,json; print(json.load(sys.stdin)["key"])' 2>/dev/null
}

log "minting a Grafana service account token"
GRAFANA_TOKEN="$(mint_grafana_token || true)"

if [[ -n "${GRAFANA_TOKEN}" && "${GRAFANA_TOKEN}" == glsa_* ]]; then
  k -n "${NS_HOLMES}" create secret generic grafana-api-key \
    --from-literal=api-key="${GRAFANA_TOKEN}" \
    --dry-run=client -o yaml | k apply -f - >/dev/null
  ok "grafana-api-key (Viewer service account)"
else
  warn "could not mint a Grafana token; the grafana/dashboards toolset will be disabled"
  k -n "${NS_HOLMES}" create secret generic grafana-api-key \
    --from-literal=api-key="" \
    --dry-run=client -o yaml | k apply -f - >/dev/null
fi

# ---------------------------------------------------------------------------
# GitHub
# ---------------------------------------------------------------------------
GITHUB_ENABLED=false
if [[ -n "${GITHUB_PAT}" ]]; then
  k -n "${NS_HOLMES}" create secret generic github-mcp-token \
    --from-literal=token="${GITHUB_PAT}" \
    --dry-run=client -o yaml | k apply -f - >/dev/null
  GITHUB_ENABLED=true
  ok "github-mcp-token"
else
  warn "GITHUB_PAT unset - skipping the GitHub MCP integration"
fi

# ---------------------------------------------------------------------------
# Endpoint overlay.
#
# Generated rather than hardcoded in values/holmes.yaml so every in-cluster URL
# has exactly one definition, in lib/versions.sh.
# ---------------------------------------------------------------------------
OVERLAY="${STATE_DIR}/holmes-endpoints.yaml"
cat > "${OVERLAY}" <<EOF
# GENERATED by scripts/70-holmesgpt.sh - do not edit.
toolsets:
  prometheus/metrics:
    config:
      prometheus_url: "${URL_VMSINGLE}"
  victorialogs:
    config:
      api_url: "${URL_VICTORIALOGS}"
  grafana/dashboards:
    config:
      api_url: "${URL_GRAFANA}"

modelList:
  default:
    model: "${HOLMES_MODEL}"
    api_key: "envRef:OPENROUTER_API_KEY"

config:
  model: default

mcpAddons:
  github:
    enabled: ${GITHUB_ENABLED}
EOF
dim "     wrote ${OVERLAY#"${REPO_ROOT}/"}"

# ---------------------------------------------------------------------------
# Install
# ---------------------------------------------------------------------------
log "installing the holmes chart"
h upgrade --install "${REL_HOLMES}" robusta/holmes \
  --version "${VER_HOLMES}" \
  --namespace "${NS_HOLMES}" \
  --values "${REPO_ROOT}/values/holmes.yaml" \
  --values "${OVERLAY}" \
  --wait --timeout 10m

wait_rollout "${NS_HOLMES}" 5m

# ---------------------------------------------------------------------------
# Ask Holmes which of its integrations actually connected. This is the real
# integration test: the chart installing cleanly says nothing about whether
# VictoriaLogs or Grafana are reachable.
# ---------------------------------------------------------------------------
log "querying HolmesGPT"
sleep 10

if model_json=$(incluster_curl "${NS_HOLMES}" "${URL_HOLMES}/api/model" 2>/dev/null) \
   && [[ -n "${model_json}" ]]; then
  ok "Holmes API responding: $(printf '%s' "${model_json}" | head -c 160)"
else
  warn "Holmes API not answering yet; check: kubectl -n ${NS_HOLMES} logs deploy/${HOLMES_FULLNAME}"
fi

ok "HolmesGPT ready"
