#!/usr/bin/env bash
# Chat UI for HolmesGPT: build holmes-bridge (holmes-bridge/) on the minikube
# node, deploy it, then install Open WebUI pointed at it.
#
#   holmes-bridge exposes HolmesGPT as an OpenAI-compatible model and keeps
#   every conversation, request and tool call in SQLite.
set -euo pipefail
source "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/lib/common.sh"
load_env
setup_docker_config

step "Open WebUI ${VER_OPENWEBUI} + holmes-bridge"

ensure_ns "${NS_HOLMES}"

# ---------------------------------------------------------------------------
# holmes-bridge image.
#
# Built with the node's container runtime (`minikube image build`), so no Go
# toolchain is needed on this machine and the image lands directly in the
# node's image store without a registry. The tag is a hash of the source tree:
# unchanged source means no rebuild, changed source means a new tag and
# therefore a rollout.
# ---------------------------------------------------------------------------
BRIDGE_SRC="${REPO_ROOT}/holmes-bridge"
bridge_hash=$(
  cd "${BRIDGE_SRC}" \
  && find . -type f ! -name '*_test.go' ! -name 'README.md' -print0 \
     | sort -z | xargs -0 shasum -a 256 | shasum -a 256 | cut -c1-12
)
BRIDGE_IMAGE="${BRIDGE_IMAGE_REPO}:src-${bridge_hash}"

if minikube -p "${MINIKUBE_PROFILE}" image ls 2>/dev/null | grep -q "/${BRIDGE_IMAGE}$"; then
  ok "image ${BRIDGE_IMAGE} already on the node"
else
  log "building ${BRIDGE_IMAGE} on the node (first build downloads the Go toolchain image)"
  minikube -p "${MINIKUBE_PROFILE}" image build -t "${BRIDGE_IMAGE}" "${BRIDGE_SRC}" 2>&1 \
    | grep -v '^#[0-9]* \(DONE\|CACHED\|\.\.\.\|sha256\|extracting\|resolve\|transferring\)' \
    | sed 's/^/     /' || true
  minikube -p "${MINIKUBE_PROFILE}" image ls 2>/dev/null | grep -q "/${BRIDGE_IMAGE}$" \
    || die "image build failed: ${BRIDGE_IMAGE} is not on the node"
  ok "built ${BRIDGE_IMAGE}"
fi

# ---------------------------------------------------------------------------
# Deploy the bridge
# ---------------------------------------------------------------------------
log "deploying ${BRIDGE_NAME}"
sed -e "s|__NAME__|${BRIDGE_NAME}|g" \
    -e "s|__NAMESPACE__|${NS_HOLMES}|g" \
    -e "s|__IMAGE__|docker.io/library/${BRIDGE_IMAGE}|g" \
    -e "s|__HOLMES_URL__|${URL_HOLMES}|g" \
    -e "s|__MODEL_ID__|${BRIDGE_MODEL_ID}|g" \
    "${REPO_ROOT}/manifests/holmes-bridge/bridge.yaml" \
  | k apply -f - >/dev/null
wait_rollout "${NS_HOLMES}" 5m "deployment/${BRIDGE_NAME}"
ok "${BRIDGE_NAME} rolled out"

# ---------------------------------------------------------------------------
# Open WebUI. The bridge URL is generated here so it is defined once, in
# lib/versions.sh, like every other in-cluster endpoint.
# ---------------------------------------------------------------------------
OVERLAY="${STATE_DIR}/openwebui-endpoints.yaml"
cat > "${OVERLAY}" <<YAML
# GENERATED by scripts/75-openwebui.sh - do not edit.
openaiBaseApiUrl: "${URL_HOLMES_BRIDGE}/v1"
YAML
dim "     wrote ${OVERLAY#"${REPO_ROOT}/"}"

log "installing the open-webui chart"
h upgrade --install "${REL_OPENWEBUI}" open-webui/open-webui \
  --version "${VER_OPENWEBUI}" \
  --namespace "${NS_HOLMES}" \
  --values "${REPO_ROOT}/values/open-webui.yaml" \
  --values "${OVERLAY}" \
  --wait --timeout 15m

wait_rollout "${NS_HOLMES}" 10m "statefulset/${OPENWEBUI_FULLNAME}"

# ---------------------------------------------------------------------------
# Verify the chain UI -> bridge -> Holmes end to end, without an LLM call.
# ---------------------------------------------------------------------------
# The Deployment uses Recreate, so the Service has no endpoint for a few
# seconds after the rollout is reported complete.
log "checking holmes-bridge"
bridge_lists_model() {
  models=$(incluster_curl "${NS_HOLMES}" "${URL_HOLMES_BRIDGE}/v1/models" 2>/dev/null) \
    && printf '%s' "${models}" | grep -q "\"id\": *\"${BRIDGE_MODEL_ID}\""
}
if retry 6 5 bridge_lists_model; then
  ok "bridge lists model '${BRIDGE_MODEL_ID}'"
else
  die "bridge did not list model '${BRIDGE_MODEL_ID}': ${models:-no response}"
fi
if ready=$(incluster_curl "${NS_HOLMES}" "${URL_HOLMES_BRIDGE}/readyz" 2>/dev/null) \
   && printf '%s' "${ready}" | grep -q '"ok"'; then
  ok "bridge reaches HolmesGPT"
else
  warn "bridge /readyz: ${ready:-no response}"
fi

# Open WebUI takes a little while after the pod is Ready before it listens.
log "checking Open WebUI"
openwebui_healthy() {
  incluster_curl "${NS_HOLMES}" "${URL_OPENWEBUI}/health" 2>/dev/null | grep -q 'true'
}
if retry 12 10 openwebui_healthy; then
  ok "Open WebUI healthy"
else
  warn "Open WebUI /health not answering yet; check: kubectl -n ${NS_HOLMES} logs statefulset/${OPENWEBUI_FULLNAME}"
fi

ok "Open WebUI ready"
dim "     kubectl --context ${MINIKUBE_PROFILE} -n ${NS_HOLMES} port-forward svc/${OPENWEBUI_FULLNAME} 8080:80   ->  http://localhost:8080"
